version: '2'
services:
  redis:
    image: redis
    ports:
      - 6666:6379
  web:
    environment:
      - TZ=Asia/Shanghai
    image: m2micro/m2mfa-pad:2.5.0-SNAPSHOT
    build:
      context: .
      args:
        - JAR_FILE=target/m2mfa-2.5.0-SNAPSHOT.jar
      dockerfile: Dockerfile
    ports:
      - 9000:8081
      - 8089:8089
