version: '2'
services:
  redis-mes:
    image: redis
  web:
    environment:
      - TZ=Asia/Shanghai
    image: m2micro/m2mfa-pad:2.6.0-snapshot
    build:
      context: .
      args:
        - JAR_FILE=target/m2mfa-2.6.0-SNAPSHOT.jar
      dockerfile: Dockerfile
    ports:
      - 9000:8081
      - 8089:8089
