spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/factory_application?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root

  cache:
    type: redis
  redis:
    host: 192.168.2.20
    port: 6379
  activemq:
    user: admin
    password: admin
    broker-url: tcp://192.168.1.132:61616