spring:
  datasource:
    secondary:
      jdbc-url: jdbc:mysql://192.168.2.24:3306/mes?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
      username: root
      password: ABCabc@123
      driverClassName: com.mysql.jdbc.Driver
      druid:
        max-active: 10
        min-idle: 2
        max-wait: 60000
        initial-size: 5
    primary:
        jdbc-url: jdbc:oracle:thin:@10.9.7.217:1521:topprod
        username: HWSZW
        password: HWSZW
        driver-class-name: oracle.jdbc.OracleDriver
  cache:
    type: redis
  redis:
    host: 192.168.1.111
    port: 6379

m2miot:
  client:
    url: http://192.168.1.111:8082
file:
  baseDir: /home/test001/m2m_mes/files
labServer:
  url: http://192.168.2.16:9666/api/
kanban:
  url: http://192.168.1.111:8085
  port: 8089
