server:
  tomcat:
    uri-encoding: UTF-8
  port: 8081
  servlet:
    context-path: /

spring:
  profiles:
    active: dev


swagger:
  title: M2Micro api
  description: M2Micro 企业后台工厂应用
  version: 1.0
  license: Apache License, Version 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfServiceUrl: http://www.m2micro.com
  base-package: com.m2micro.m2mfa

scheduletask:
  companyID: process001
  address：: http://monitor.m2micro.cn




