spring:
  datasource:
    url: jdbc:mysql://192.168.1.132:3306/factory_application?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password:

  cache:
    type: redis
  redis:
    host: 192.168.2.20
    port: 6379


