server:
  tomcat:
    uri-encoding: UTF-8
  port: 8081
  servlet:
    context-path: /

spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #如果使用字符串表示，用这行设置格式
    timezone: GMT+8

  resources:
    static-locations: classpath:/META-INF/resources/webjars/m2mfa-ui, classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/, classpath:/public/
swagger:
  title: M2Micro api
  description: M2Micro 企业后台工厂应用
  version: 1.0
  license: Apache License, Version 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfServiceUrl: http://www.m2micro.com
  base-package: com.m2micro

scheduletask:
  companyID: process001
  address：: http://monitor.m2micro.cn

m2mfa:
  version: @project.version@
  iot:
    processId: F5A936ED96074714AEA9E90E9B5B2F35 #(注塑成型工艺id)排产单ID找模具ID是只找注塑成型工序的模具
file:
  baseDir:
labServer:
  url: http://192.168.2.16:9666/api/




